import type { Job, Application } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Marketing Manager",
    company: "TechCorp",
    platform: "indeed",
    status: "new",
    date_found: "2026-03-27",
    link: "#",
    description: "Lead marketing initiatives for a fast-growing SaaS company.",
  },
  {
    id: "2",
    title: "Content Strategist",
    company: "RemoteFirst Inc",
    platform: "remoteok",
    status: "applied",
    date_found: "2026-03-26",
    link: "#",
  },
  {
    id: "3",
    title: "Growth Marketing Lead",
    company: "StartupXYZ",
    platform: "wellfound",
    status: "interview",
    date_found: "2026-03-25",
    link: "#",
  },
  {
    id: "4",
    title: "Digital Marketing Specialist",
    company: "BigCo",
    platform: "indeed",
    status: "applied",
    date_found: "2026-03-25",
    link: "#",
  },
  {
    id: "5",
    title: "SEO Manager",
    company: "SearchPro",
    platform: "remoteok",
    status: "rejected",
    date_found: "2026-03-24",
    link: "#",
  },
  {
    id: "6",
    title: "Product Marketing Manager",
    company: "CloudBase",
    platform: "wellfound",
    status: "new",
    date_found: "2026-03-27",
    link: "#",
  },
  {
    id: "7",
    title: "Email Marketing Lead",
    company: "MailFlow",
    platform: "indeed",
    status: "applied",
    date_found: "2026-03-23",
    link: "#",
  },
  {
    id: "8",
    title: "Brand Manager",
    company: "DesignHub",
    platform: "remoteok",
    status: "new",
    date_found: "2026-03-27",
    link: "#",
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "a1",
    job_id: "2",
    title: "Content Strategist",
    company: "RemoteFirst Inc",
    platform: "remoteok",
    date_applied: "2026-03-26",
    status: "applied",
    cover_letter:
      "Hey — saw your Content Strategist role. I've been doing content and marketing automation for 3 years. I write clearly, plan content calendars, and know how to tie content to growth metrics. Happy to chat about how I'd approach your content pipeline.",
  },
  {
    id: "a2",
    job_id: "3",
    title: "Growth Marketing Lead",
    company: "StartupXYZ",
    platform: "wellfound",
    date_applied: "2026-03-25",
    status: "interview",
    cover_letter:
      "Hi — your Growth Marketing Lead position caught my eye. I've scaled acquisition channels from zero for two startups. I focus on what moves numbers, not vanity metrics. Would love to discuss your current growth stack.",
  },
  {
    id: "a3",
    job_id: "4",
    title: "Digital Marketing Specialist",
    company: "BigCo",
    platform: "indeed",
    date_applied: "2026-03-25",
    status: "applied",
  },
  {
    id: "a4",
    job_id: "5",
    title: "SEO Manager",
    company: "SearchPro",
    platform: "remoteok",
    date_applied: "2026-03-24",
    status: "rejected",
  },
  {
    id: "a5",
    job_id: "7",
    title: "Email Marketing Lead",
    company: "MailFlow",
    platform: "indeed",
    date_applied: "2026-03-23",
    status: "applied",
  },
];

export const MOCK_STATS = {
  total_jobs: 47,
  total_applications: 23,
  applications_today: 3,
  response_rate: 0.13,
};
