"use client";

import { useState } from "react";

const QUESTIONS = [
  {
    q: "How does auto-apply work?",
    a: "Our Chrome extension runs in the background on Indeed. It reads job listings, fills out application forms with your profile data, attaches your resume, and submits — all automatically. You set filters so it only applies to relevant jobs.",
  },
  {
    q: "Which job platforms are supported?",
    a: "We currently support Indeed, RemoteOK, and Wellfound. Free users get RemoteOK only. Pro users get all platforms, with new ones being added regularly.",
  },
  {
    q: "Will my applications look spammy?",
    a: "No. Each cover letter is uniquely generated by AI based on the specific job description and your profile. Applications are submitted one at a time with realistic timing, not bulk-blasted.",
  },
  {
    q: "How does AI write cover letters?",
    a: "We use Claude AI to analyze your resume, writing style samples, and the job description. It generates a personalized cover letter that matches your tone and highlights relevant experience for each specific role.",
  },
  {
    q: "Is my resume data secure?",
    a: "Yes. Your data is stored on Supabase with row-level security. Resumes are in encrypted storage. We never sell your data or share it with third parties beyond the job platforms you apply to.",
  },
  {
    q: "Can I control which jobs get applied to?",
    a: "Absolutely. You set keywords, locations, job types, salary ranges, and excluded companies. The AI only applies to jobs matching your filters. You can review applications in your dashboard.",
  },
  {
    q: "What happens after the free trial?",
    a: "The free plan stays free forever with limited features (5 apps/day, 1 platform). To unlock all platforms, 50 apps/day, and AI cover letters, upgrade to Pro for $16/month. Cancel anytime.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-[#E8E8F0]">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-5 text-left group"
      >
        <span className="text-base font-medium text-[#1A1A2E] pr-4 group-hover:text-[#6C5CE7] transition-colors">
          {q}
        </span>
        <span
          className="shrink-0 w-6 h-6 flex items-center justify-center text-[#6B6B8A] transition-transform duration-300"
          style={{ transform: open ? "rotate(45deg)" : "rotate(0deg)" }}
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4v16m8-8H4" />
          </svg>
        </span>
      </button>
      <div
        className="overflow-hidden transition-all duration-300"
        style={{ maxHeight: open ? "200px" : "0px", opacity: open ? 1 : 0 }}
      >
        <p className="text-sm text-[#6B6B8A] leading-relaxed pb-5">{a}</p>
      </div>
    </div>
  );
}

export default function FAQ() {
  return (
    <section id="faq" className="py-20 px-4 sm:px-6 lg:px-8 bg-white">
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_1.5fr] gap-12 lg:gap-20">
          {/* Left — title */}
          <div className="lg:sticky lg:top-32 lg:self-start">
            <h2
              className="text-3xl sm:text-4xl font-bold text-[#1A1A2E]"
              style={{ fontFamily: "'Syne', sans-serif" }}
            >
              Frequently<br />asked<br />questions
            </h2>
            <p className="mt-4 text-[#6B6B8A]">
              Everything you need to know about JobFlow.
            </p>
          </div>

          {/* Right — accordion */}
          <div>
            {QUESTIONS.map((item) => (
              <FAQItem key={item.q} q={item.q} a={item.a} />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
